services:
  gophish:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
      - "8080:8080"
      - "8443:8443"
      - "80:80"
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/gophish?sslmode=disable
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gophish
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: